### ISSUE TITLE
Add application functionality to README

### ISSUE THREAD

**Issue by cj13579** [Boemska/covid-19-sas#1]
At the moment the README in the App folder just contains technical information on how to install the front-end dependencies and start the App in development mode. I think that we should add more detail in this guide about what the functionality of this app is and how someone using this application can get it up and running in their environment. Specifically, I think that we need to include information on the following:

* That this app is based on the [Carbon CSA](https://github.com/Boemska/create-sas-app) and has all the core functionality of that
* How to connect the front end elements of this application with the model found in the CCF folder (and how to deploy that model so that it can be used by this app).
* How to use the scenario generation/modification functionality of this app
* How to use and understand the charts that are generated by this app

**Comment by boomskats** [comment]
Ok, nice one. I think we need to ask for some help from the experts for that last point, but i'll put together the rest of this.
