### ISSUE TITLE
App should display all model results

### ISSUE THREAD

**Issue by cj13579** [Boemska/covid-19-sas#2]
At the moment, when you get the results back from the model we are only displaying one of the four sets of results that are returned from SAS. In addition, we don't actually list anywhere which model types we are displaying. We need to work out how best to display the results of all of the different models that are run and a way to nicely label and distinguish them.

![image](https://user-images.githubusercontent.com/1965454/85768231-3290a280-b6ef-11ea-85d0-5cc805bb001a.png)

**Comment by boomskats** [comment]
I think the decision we had to make here was whether we wanted users to be able to select which model(s) are run as part of each scenario submission. But that should be independent. This is what the last design for this page looks like, with the hover panel that shows an 'overview of input parameters' when the user has scrolled the inputs out of view. The output model selection tabs are there, check it out. 

![Selection_178](https://user-images.githubusercontent.com/11962123/85785067-d5154980-b720-11ea-8752-e980f3b64935.png)

Also not quite sure what to do about those tiles - whether we get the data for them from the sas code or figure it out at the front end. Ideally it should all be done by the model calcs...

**Comment by bozazec** [comment]
Closed with https://github.com/Boemska/covid-19-sas/pull/12
