### ISSUE TITLE
QR code share mechanism can be updated to upstream CSA

### ISSUE THREAD

**Issue by boomskats** [Boemska/covid-19-sas#7]
This is the share screen this project uses at the moment:

![Selection_210](https://user-images.githubusercontent.com/11962123/86360297-0da9ab80-bc6a-11ea-9277-14a0bd8f2f52.png)

At some point we should update it with the one from the upstream carbon CSA:

![image](https://user-images.githubusercontent.com/11962123/86360630-87419980-bc6a-11ea-9502-fda9f4b6d175.png)

**Comment by bozazec** [comment]
Closed with https://github.com/Boemska/covid-19-sas/pull/9
